language: generic

sudo: required

services:
  - docker
  
before_install:
  - useradd -m isabelle && (echo isabelle:isabelle | chpasswd)
  - chown -R isabelle:isabelle *
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - ./bin/cloud_build.sh
